INSERT INTO model_peak (id, name, distance, checked) VALUES (1, 'Carrauntoohil', 1039, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (2, 'Lugnaquilla', 925, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (3, 'Galtymore', 919, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (4, 'Mweelrea', 814, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (5, 'Mount Leinster', 795, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (6, 'Knockboy', 706, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (7, 'Slieve Donard', 850, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (8, 'Errigal', 751, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (9, 'Kippure', 757, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (10, 'Slieve Gullion', 573, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (11, 'Slieve Foye', 589, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (12, 'Cuilcagh', 665, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (13, 'Truskmore SE Top', 647, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (14, 'Binn Bhán (Ben Baun)', 729, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (15, 'Sawel', 678, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (16, 'Arderin', 527, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (17, 'Brandon Hill', 515, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (18, 'Cupidstown Hill', 379, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (19, 'Slieve Beagh East', 366, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (20, 'Corrie Mountain', 422, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (21, 'Trostan', 550, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (22, 'Moylussa', 532, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (23, 'Truskmore', 647, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (24, 'Knockmealdown', 794, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (25, 'Mullaghmeen', 258, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (26, 'Corn Hill', 278, false);
INSERT INTO model_peak (id, name, distance, checked) VALUES (27, 'Lough Crew/ Slieve Na Calliagh', 279, false);
